### ISSUE TITLE
The current state of the lib

### ISSUE THREAD

**Issue by KrestM** [nolia/Noodle#10]
Hello! 
I can see that the last release tag was in 2017 but then you had some commits with different fixes. 
The question is about releases because I wouldn't want to be dependent on SNAPSHOT, but it looks like it doesn't make sense to copy the whole library as well because I can see that there is an active branch with "kotlin" name where you rewrite the lib.
Is it possible to return back to releases with bug fixes and so on or next release will be only with Kotlin stuff?
Thanks!

**Comment by nolia** [comment]
Hello, and thanks for the interest.

First, you noticed correctly, the version 1.0 is planned to be written entirely in Kotlin, while targeting JVM platforms. 
Meanwhile, I do plan to have some intermediate release, with a couple of bug-fixes, and some API changes/enhancements.
And finally, I cannot give any estimates on the timing of these releases.
So, as usual, issues and PRs are pretty much welcome 👍
