### ISSUE TITLE
Objects List with Inner List

### ISSUE THREAD

**Issue by chemickypes** [nolia/Noodle#8]
I've a collection of object. Every Object has a list inside: have I to put id in the inner list elements?

**Comment by nolia** [comment]
If you store original objects in a Noodle collection, then you just update those objects. Inner list is just a part of original object. Nested objects are not indexed in Noodle and you can only access them by accessing outer objects. 
Also, there are no many-to-many mapping in Noodle or other kind of relations.

**Comment by chemickypes** [comment]
Ok, I understand! Thanks a lot!
