### ISSUE TITLE
DeleteAll in collection

### ISSUE THREAD

**Issue by chemickypes** [nolia/Noodle#9]
Hi, is there a way to make a `deleteAll()` on a collection?

**Comment by nolia** [comment]
There are no `deleteAll()` method in `Collection` interface yet. (Though it's planned for 1.0)
What you can do is: get all items with `all()` and delete each one using their ids.

Also, pull requests are welcome 😃

**Comment by chemickypes** [comment]
Great! Thanks! 
I've to finish any project and than I'll make this fix and than I'll put the pull request!

**Comment by chemickypes** [comment]
I saw that in dev branch there is `deleteAll` method.

```java
@Override
  public Result<Boolean> deleteAll() {
    return new Result<>(new Callable<Boolean>() {
      @Override
      public Boolean call() throws Exception {
        for (byte[] key : getAllCollectionKeys()) {
          storage.remove(key);
        }
        return Boolean.TRUE;
      }
    });
  }
```

We can close this issue! ;)

**Comment by nolia** [comment]
It's probably not the final form, but yes, thank you)

чт, 18 янв. 2018 г. в 16:17, Angelo Moroni <notifications@github.com>:
